services:
  manager:
    container_name: manager
    build:
      context: .
      dockerfile: Manager/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - worker
    environment:
      - PartCount=1
    networks:
      - crackhash-net

  worker:
    container_name: worker
    build:
      context: .
      dockerfile: Worker/Dockerfile
    networks:
      - crackhash-net

networks:
  crackhash-net:
