services:
  manager:
    image: manager
    environment:
      - WORKER_COUNT=1
    ports:
      - "8080:8080"
    depends_on:
      - worker
    networks:
      - crackhash-net

  worker:
    image: worker
    deploy:
      replicas: 1
    networks:
      - crackhash-net

networks:
  crackhash-net:
